<template>
  <svg style="display: none">
    <filter
      id="container-glass"
      x="0%"
      y="0%"
      width="100%"
      height="100%"
    >
      <feTurbulence
        type="fractalNoise"
        baseFrequency="0.002 0.002"
        numOctaves="3"
        seed="2"
        result="noise"
      />
      <feGaussianBlur
        in="noise"
        stdDeviation="0.01"
        result="blur"
      />
      <feDisplacementMap
        in="SourceGraphic"
        in2="blur"
        scale="42"
        xChannelSelector="R"
        yChannelSelector="G"
      />
    </filter>
  </svg>
</template>
